# Generated by Django 5.0.6 on 2024-06-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0002_terst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='terst',
        ),
        migrations.AlterField(
            model_name='user_contact',
            name='Contact_no',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
