# Generated by Django 4.2.13 on 2024-06-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0008_alter_rental_books_user_rent_complete_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_books_user',
            name='rent_complete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental_books_user',
            name='rent_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
