# Generated by Django 5.0.6 on 2024-06-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0009_alter_rental_books_user_rent_complete_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rental_books_user',
        ),
    ]
