# Generated by Django 5.0.6 on 2024-06-18 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0010_delete_rental_books_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rental_books_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rent_start_at', models.DateTimeField(blank=True, null=True)),
                ('rent_complete_at', models.DateTimeField(blank=True, null=True)),
                ('renter_duration', models.DurationField(default=0)),
                ('renter_page_book', models.IntegerField(default=0)),
                ('rent_of_book', models.IntegerField(default=0)),
                ('book', models.ForeignKey(blank=True, db_column='book_for_rent', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_rental', to='book_rent_task.books')),
                ('user', models.ForeignKey(blank=True, db_column='rental_user', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rental', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
