# Generated by Django 5.0.6 on 2024-06-19 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0016_rename_books_data_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_books_user',
            name='renter_duration',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
