# Generated by Django 5.0.6 on 2024-06-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0018_book_alter_rental_books_user_book_delete_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
