# Generated by Django 5.0.6 on 2024-06-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='terst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
