# Generated by Django 4.2.13 on 2024-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='total_book_renters',
            field=models.IntegerField(default=0),
        ),
    ]
