# Generated by Django 5.0.6 on 2024-06-19 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0011_rental_books_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='books',
            name='updated_at',
        ),
    ]
