# Generated by Django 5.0.6 on 2024-06-19 05:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0014_remove_rental_books_user_rent_complete_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='Books_data',
        ),
    ]
