# Generated by Django 5.0.6 on 2024-06-19 05:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0015_rename_books_books_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books_data',
            new_name='books',
        ),
    ]
