# Generated by Django 5.0.6 on 2024-06-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0020_alter_rental_books_user_renter_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_books_user',
            name='renter_page_book',
            field=models.FloatField(default=0),
        ),
    ]
