# Generated by Django 5.0.6 on 2024-06-19 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0021_alter_rental_books_user_renter_page_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_books_user',
            name='renter_duration',
            field=models.IntegerField(default=datetime.timedelta(days=30)),
        ),
    ]
