# Generated by Django 5.0.6 on 2024-06-20 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_rent_task', '0024_book_is_admin_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
    ]
